---
exclude: .git|.dvc|.bzr|.direnv|.eggs|.mypy_cache|.tox|.venv|__packages__|_build|build|dist|venv
default_stages: [commit]
fail_fast: true
repos:
  - repo: https://github.com/lyz-code/yamlfix/
    rev: 1.11.0
    hooks:
      - id: yamlfix
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-toml
      - id: check-merge-conflict
      - id: check-ast
      - id: check-added-large-files
      - id: requirements-txt-fixer
  - repo: https://github.com/hakancelikdev/unimport
    rev: 0.16.0
    hooks:
      - id: unimport
        args: [--disable-auto-discovery-config, --config=pyproject.toml]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.274
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  # - repo: https://github.com/asottile/pyupgrade
  #   rev: v3.3.2
  #   hooks:
  #     - id: pyupgrade
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
      - id: black-jupyter
        language_version: python3.10
  # - repo: https://github.com/pycqa/isort
  #   rev: 76a71b13dab48f59cc1c006806f04bde1fe19b6d
  #   hooks:
  #     - id: isort
  #       name: isort (python)
  - repo: https://github.com/MarcoGorelli/auto-walrus
    rev: v0.2.2
    hooks:
      - id: auto-walrus
  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
      - id: nbstripout
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.0
    hooks:
      - id: nbqa-black
        language_version: python3.10
        additional_dependencies: [black==23.3.0]
      - id: nbqa-ruff
        args: [--fix, --exit-non-zero-on-fix]
      # - id: nbqa-isort
      #   additional_dependencies: [isort==5.12.0]
      # - id: nbqa-flake8
      #   additional_dependencies: [flake8, flake8-isort]
      # - id: nbqa-pylint
      #   args: [--disable=E0401, --disable=W9008, --disable=R0914]
      - id: nbqa-mypy
        args: [--ignore-missing-imports]
        additional_dependencies: [tokenize-rt==3.2.0, mypy==v1.2.0]
      - id: nbqa-pyupgrade
      - id: nbqa-check-ast
  - repo: https://github.com/python-poetry/poetry
    rev: 1.5.0
    hooks:
      - id: poetry-export
        args:
          - -f
          - requirements.txt
          - -o
          - requirements.txt
          - --without-hashes
  # - repo: https://github.com/pycqa/flake8
  #   rev: d016204366a22d382b5b56dc14b6cbff28ce929e
  #   hooks:
  #     - id: flake8
  #       additional_dependencies: [flake8-isort]
  # - repo: local
  #   hooks:
  #     - id: pylint
  #       name: pylint
  #       entry: poetry run pylint
  #       language: system
  #       types: [python]
  #       args:
  #         - -rn  # Only display messages
  #         - -sn  # Don't display the score
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.4.0
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]
        additional_dependencies: [tokenize-rt==3.2.0]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
      - id: codespell
        additional_dependencies: [tomli]
        args: [--exclude-file=poetry.lock]
